[package]
name = "grrs"
version = "0.1.0"
authors = ["Markus Strasser <strasser.ms@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

glsp = "0.2.0"
